package net.pometia.dragonshoard.item;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.pometia.dragonshoard.DragonsHoard;
import net.pometia.dragonshoard.block.ModBlocks;
import net.pometia.dragonshoard.fluid.ModFluids;

import java.util.function.Supplier;

public class ModCreativeModeTabs {

    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, DragonsHoard.MOD_ID);

    public static final Supplier<CreativeModeTab> DRAGONSHOARD_TAB =
            CREATIVE_MODE_TABS.register("dragonshoard_tab", () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup.dragonshoard.dragonshoard_tab"))
                    .icon(() -> new ItemStack(ModBlocks.STAR_BLUE_GOLD_BLOCK.get()))
                    .displayItems((parameters, output) -> {
                        output.accept(ModBlocks.SILVER_BLOCK);
                        output.accept(ModBlocks.WHITE_GOLD_BLOCK);
                        output.accept(ModBlocks.BLUE_GOLD_BLOCK);
                        output.accept(ModBlocks.ROSE_GOLD_BLOCK);
                        output.accept(ModBlocks.STAR_BLUE_GOLD_BLOCK);
                        output.accept(ModBlocks.MOONSTONE_CRYSTAL);
                        output.accept(ModBlocks.IOLITE_CRYSTAL);
                        output.accept(ModBlocks.AQUAMARINE_CRYSTAL);
                        output.accept(ModBlocks.ROSE_QUARTZ_CRYSTAL);
                        output.accept(ModBlocks.VERDELITE_CRYSTAL);
                        output.accept(ModBlocks.ALEXANDRITE_CRYSTAL);
                        output.accept(ModBlocks.RUBY_CRYSTAL);
                        output.accept(ModBlocks.SAPPHIRE_CRYSTAL);
                        output.accept(ModBlocks.TOURMALINE_CRYSTAL);
                        output.accept(ModBlocks.TANZANITE_CRYSTAL);
                        output.accept(ModBlocks.CITRINE_CRYSTAL);
                        output.accept(ModBlocks.OPAL_CRYSTAL);
                        output.accept(ModBlocks.MOONSTONE_BLOCK);
                        output.accept(ModBlocks.IOLITE_BLOCK);
                        output.accept(ModBlocks.AQUAMARINE_BLOCK);
                        output.accept(ModBlocks.ROSE_QUARTZ_BLOCK);
                        output.accept(ModBlocks.VERDELITE_BLOCK);
                        output.accept(ModBlocks.ALEXANDRITE_BLOCK);
                        output.accept(ModBlocks.RUBY_BLOCK);
                        output.accept(ModBlocks.SAPPHIRE_BLOCK);
                        output.accept(ModBlocks.TOURMALINE_BLOCK);
                        output.accept(ModBlocks.TANZANITE_BLOCK);
                        output.accept(ModBlocks.CITRINE_BLOCK);
                        output.accept(ModBlocks.OPAL_BLOCK);
                        output.accept(ModBlocks.JAN_IDOL);
                        output.accept(ModBlocks.FEB_IDOL);
                        output.accept(ModBlocks.MAR_IDOL);
                        output.accept(ModBlocks.APR_IDOL);
                        output.accept(ModBlocks.MAY_IDOL);
                        output.accept(ModBlocks.JUN_IDOL);
                        output.accept(ModBlocks.JUL_IDOL);
                        output.accept(ModBlocks.AUG_IDOL);
                        output.accept(ModBlocks.SEP_IDOL);
                        output.accept(ModBlocks.OCT_IDOL);
                        output.accept(ModBlocks.NOV_IDOL);
                        output.accept(ModBlocks.DEC_IDOL);
                        //output.accept(ModBlocks.FORGE_TANK);
                        output.accept(ModFluids.MOLTEN_GOLD_BUCKET);
                        output.accept(ModFluids.MOLTEN_SILVER_BUCKET);
                        output.accept(ModFluids.MOLTEN_COPPER_BUCKET);
                        output.accept(ModFluids.MOLTEN_WHITE_GOLD_BUCKET);
                        output.accept(ModFluids.MOLTEN_BLUE_GOLD_BUCKET);
                        output.accept(ModFluids.MOLTEN_ROSE_GOLD_BUCKET);
                        output.accept(ModFluids.MOLTEN_STAR_GOLD_BUCKET);
                        output.accept(ModBlocks.ALEXANDRITE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.ALEXANDRITE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.ALEXANDRITE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.ALEXANDRITE_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.VERDELITE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.VERDELITE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.VERDELITE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.VERDELITE_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.ROSE_QUARTZ_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.ROSE_QUARTZ_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.ROSE_QUARTZ_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.ROSE_QUARTZ_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.OPAL_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.OPAL_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.OPAL_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.OPAL_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.SAPPHIRE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.SAPPHIRE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.SAPPHIRE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.SAPPHIRE_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.RUBY_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.RUBY_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.RUBY_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.RUBY_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.TANZANITE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.TANZANITE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.TANZANITE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.TANZANITE_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.IOLITE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.IOLITE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.IOLITE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.IOLITE_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.MOONSTONE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.MOONSTONE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.MOONSTONE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.MOONSTONE_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.TOURMALINE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.TOURMALINE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.TOURMALINE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.TOURMALINE_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.CITRINE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.CITRINE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.CITRINE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.CITRINE_CRYSTAL_STRUCTURE_4);
                        output.accept(ModBlocks.AQUAMARINE_CRYSTAL_STRUCTURE_1);
                        output.accept(ModBlocks.AQUAMARINE_CRYSTAL_STRUCTURE_2);
                        output.accept(ModBlocks.AQUAMARINE_CRYSTAL_STRUCTURE_3);
                        output.accept(ModBlocks.AQUAMARINE_CRYSTAL_STRUCTURE_4);
                                        output.accept(ModBlocks.GOLDEN_GILDED_MOONSTONE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_MOONSTONE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_MOONSTONE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_MOONSTONE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_MOONSTONE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_MOONSTONE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_IOLITE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_IOLITE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_IOLITE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_IOLITE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_IOLITE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_IOLITE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_AQUAMARINE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_AQUAMARINE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_AQUAMARINE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_AQUAMARINE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_AQUAMARINE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_AQUAMARINE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_ROSE_QUARTZ_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_ROSE_QUARTZ_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_ROSE_QUARTZ_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_ROSE_QUARTZ_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_ROSE_QUARTZ_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_ROSE_QUARTZ_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_VERDELITE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_VERDELITE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_VERDELITE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_VERDELITE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_VERDELITE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_VERDELITE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_ALEXANDRITE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_ALEXANDRITE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_ALEXANDRITE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_ALEXANDRITE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_ALEXANDRITE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_ALEXANDRITE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_RUBY_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_RUBY_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_RUBY_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_RUBY_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_RUBY_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_RUBY_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_SAPPHIRE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_SAPPHIRE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_SAPPHIRE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_SAPPHIRE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_SAPPHIRE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_SAPPHIRE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_TOURMALINE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_TOURMALINE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_TOURMALINE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_TOURMALINE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_TOURMALINE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_TOURMALINE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_TANZANITE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_TANZANITE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_TANZANITE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_TANZANITE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_TANZANITE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_TANZANITE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_CITRINE_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_CITRINE_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_CITRINE_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_CITRINE_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_CITRINE_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_CITRINE_BLOCK);
                                output.accept(ModBlocks.GOLDEN_GILDED_OPAL_BLOCK);
                                output.accept(ModBlocks.WHITE_GILDED_OPAL_BLOCK);
                                output.accept(ModBlocks.BLUE_GILDED_OPAL_BLOCK);
                                output.accept(ModBlocks.ROSE_GILDED_OPAL_BLOCK);
                                output.accept(ModBlocks.STAR_GILDED_OPAL_BLOCK);
                                output.accept(ModBlocks.SILVER_GILDED_OPAL_BLOCK);
                    }).build());


    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
